### ISSUE TITLE
Can I translate you posts to Zh_Cn {china}

### ISSUE THREAD

**Issue by chinanf-boy** [hexacta/didact#6]
[>> zh version](https://github.com/chinanf-boy/didact-explain)

**Comment by chinanf-boy** [comment]
the last post  Didact.Fibre 
I watching and understand ing , 😔

**Comment by pomber** [comment]
Awesome! Do you want to add a link in the readme?
Something like "Other languages: ..."

**Comment by chinanf-boy** [comment]
i think , if can. but the style of link i dont know

**Comment by chinanf-boy** [comment]
l will try a little while

**Comment by chinanf-boy** [comment]
@pomber 
i pull in  #7

**Comment by chinanf-boy** [comment]
## one more thing

I hope you allow me,  Add you posts to [en-explain-lists](https://github.com/chinanf-boy/Source-Explain#didact-a-diy-guide-to-build-your-own-react-)
